/* Generated by the local organizer. Do not publish sensitive personal information. */
window.PUBLISHED_EVENT_DATA = {
  "version": 3,
  "event": {
    "title": "סוף שבוע משפחתי בצפון",
    "subtitle": "שישי עד ראשון · תכנון משותף למשפחה",
    "startDate": "2026-07-31",
    "endDate": "2026-08-02",
    "location": "כפר הורדים",
    "notes": ""
  },
  "participants": [
    "אולגה",
    "בוריס",
    "אלין",
    "אדי",
    "אינה",
    "יוני",
    "דני",
    "אביב",
    "יפעת",
    "זיו",
    "רוני",
    "מישה",
    "סשה",
    "תומה",
    "ראיה",
    "ויקה",
    "מריק",
    "וובה",
    "רחלי"
  ],
  "activeCoordinator": "רוני",
  "handoverAt": "2026-07-22T19:35:30.079Z",
  "schedule": [
    {
      "id": 1784747790023,
      "day": "Friday",
      "time": "08:30",
      "endTime": "10:30",
      "title": "יציאה - נסיעה לכפר בלום",
      "owner": "",
      "status": "proposed",
      "notes": ""
    },
    {
      "id": 1784747812105,
      "day": "Friday",
      "time": "10:30",
      "endTime": "11:00",
      "title": "הגעה לכפר בלום",
      "owner": "",
      "status": "proposed",
      "notes": ""
    },
    {
      "id": 1784747828385,
      "day": "Friday",
      "time": "11:00",
      "endTime": "13:00",
      "title": "מסלול קייקים",
      "owner": "",
      "status": "proposed",
      "notes": ""
    },
    {
      "id": 1784747864834,
      "day": "Friday",
      "time": "13:30",
      "endTime": "",
      "title": "יציאה - נסיעה לכפר הורדים",
      "owner": "",
      "status": "confirmed",
      "notes": ""
    },
    {
      "id": 1784747912309,
      "day": "Friday",
      "time": "15:00",
      "endTime": "",
      "title": "הגעה לוילה, התמקמות",
      "owner": "",
      "status": "confirmed",
      "notes": ""
    },
    {
      "id": 1784747961075,
      "day": "Friday",
      "time": "18:30",
      "endTime": "19:30",
      "title": "ארוחת ערב",
      "owner": "",
      "status": "confirmed",
      "notes": ""
    },
    {
      "id": 1784747975733,
      "day": "Friday",
      "time": "20:00",
      "endTime": "",
      "title": "אייטם תוכן",
      "owner": "",
      "status": "proposed",
      "notes": ""
    },
    {
      "id": 1784747996258,
      "day": "Saturday",
      "time": "09:30",
      "endTime": "",
      "title": "השכמות",
      "owner": "",
      "status": "confirmed",
      "notes": ""
    },
    {
      "id": 1784748014839,
      "day": "Saturday",
      "time": "10:00",
      "endTime": "11:00",
      "title": "ארוחת בוקר",
      "owner": "",
      "status": "confirmed",
      "notes": ""
    },
    {
      "id": 1784748039077,
      "day": "Saturday",
      "time": "11:00",
      "endTime": "",
      "title": "יציאה לטיול רגלי",
      "owner": "",
      "status": "confirmed",
      "notes": ""
    },
    {
      "id": 1784748141017,
      "day": "Saturday",
      "time": "13:00",
      "endTime": "",
      "title": "ארוחת צהריים",
      "owner": "",
      "status": "confirmed",
      "notes": ""
    },
    {
      "id": 1784748171763,
      "day": "Saturday",
      "time": "18:30",
      "endTime": "",
      "title": "ארוחת ערב",
      "owner": "",
      "status": "confirmed",
      "notes": ""
    },
    {
      "id": 1784748216355,
      "day": "Saturday",
      "time": "15:00",
      "endTime": "16:00",
      "title": "אייטם תוכן",
      "owner": "",
      "status": "confirmed",
      "notes": ""
    },
    {
      "id": 1784748229592,
      "day": "Saturday",
      "time": "20:00",
      "endTime": "",
      "title": "אייטם תוכן",
      "owner": "",
      "status": "confirmed",
      "notes": ""
    },
    {
      "id": 1784748242563,
      "day": "Sunday",
      "time": "09:30",
      "endTime": "",
      "title": "השכמות",
      "owner": "",
      "status": "confirmed",
      "notes": ""
    },
    {
      "id": 1784748271588,
      "day": "Sunday",
      "time": "10:00",
      "endTime": "",
      "title": "ארוחת בוקר",
      "owner": "",
      "status": "confirmed",
      "notes": ""
    },
    {
      "id": 1784748285484,
      "day": "Sunday",
      "time": "12:00",
      "endTime": "",
      "title": "צ'ק אאוט",
      "owner": "",
      "status": "confirmed",
      "notes": ""
    },
    {
      "id": 1784748308452,
      "day": "Sunday",
      "time": "",
      "endTime": "",
      "title": "אטרקציה",
      "owner": "",
      "status": "proposed",
      "notes": ""
    }
  ],
  "meals": [
    {
      "id": 101,
      "day": "Friday",
      "time": "19:00",
      "mealType": "dinner",
      "title": "ארוחת ערב שישי",
      "dishes": "בשר על האש / דג מרוקאי / אופציה טבעונית / סלטים / תוספות - תפו\"א וירקות בגריל",
      "quantity": "",
      "owner": "",
      "notes": "ציוד: על האש (לא לשכוח פחם), סיר טרמוס"
    },
    {
      "id": 1784748614713,
      "day": "Saturday",
      "time": "",
      "mealType": "breakfast",
      "title": "ארוחת בוקר שבת",
      "dishes": "ג'חנון / ביצים קשות / רסק עגבניות / לחמים",
      "quantity": "",
      "owner": "",
      "notes": "מיץ"
    },
    {
      "id": 1784748691566,
      "day": "Saturday",
      "time": "",
      "mealType": "snacks",
      "title": "נשנושים צהריים שבת",
      "dishes": "לחם / טורטיות / גבינות / פסטרמות / סלט ירקות / גבינות טבעוניות",
      "quantity": "",
      "owner": "",
      "notes": ""
    },
    {
      "id": 1784748711480,
      "day": "Saturday",
      "time": "",
      "mealType": "dinner",
      "title": "ארוחת ערב שבת",
      "dishes": "",
      "quantity": "",
      "owner": "",
      "notes": ""
    },
    {
      "id": 1784748722557,
      "day": "Sunday",
      "time": "",
      "mealType": "breakfast",
      "title": "ארוחת בוקר ראשון",
      "dishes": "",
      "quantity": "",
      "owner": "",
      "notes": ""
    }
  ],
  "tasks": [],
  "bring": [
    {
      "id": 1784748769662,
      "title": "סיר טרמוס",
      "category": "כלים",
      "quantity": "2",
      "owner": "",
      "done": false
    },
    {
      "id": 1784748784580,
      "title": "פחמים, גריל",
      "category": "על האש",
      "quantity": "",
      "owner": "",
      "done": false
    },
    {
      "id": 1784748801435,
      "title": "פלטת שבת",
      "category": "",
      "quantity": "1",
      "owner": "מישה",
      "done": false
    }
  ],
  "cars": [
    {
      "id": 1784748851550,
      "driver": "בוריס",
      "needRide": false,
      "direction": "arrival",
      "day": "Friday",
      "time": "",
      "origin": "פתח תקווה",
      "seats": 4,
      "passengers": [
        "אולגה",
        "יוני",
        "דני"
      ]
    },
    {
      "id": 1784748872986,
      "driver": "מישה",
      "needRide": false,
      "direction": "arrival",
      "day": "Friday",
      "time": "",
      "origin": "אזור",
      "seats": 3,
      "passengers": [
        "רוני"
      ]
    }
  ]
};
